version: '3.8'

services:
  apichroma:
    build: ../chroma-api
    container_name: apichroma
    ports:
      - "8000:8000"
    networks:
      - red-api

  dbchroma:
    build: ../chroma-db
    container_name: dbchroma
    ports:
      - "9000:9000"
    networks:
      - red-api

  apieesxpress:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    container_name: apieesxpress
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      CHROMA_API_URL: "http://dbchroma:9000/api/v1"
      PORT: "3000"
      NODE_ENV: "development"
    networks:
      - red-api
    depends_on:
      - dbchroma
      - apichroma

networks:
  red-api:
